@startuml hoge

namespace Player{
    class PlayerRotate
    class PlayerMove
    class PlayerDrop
    class PlayerState{
        +Vector2Int Position
        +Direction Rotation    
        +bool IsAcceptingInput
        +List<Tween> ActiveTweens
        +Item[] Items
        +bool IsBomb
        +void GroundingProcess()
        +bool CanSet(Vector2Int pos, Directoin rot)
    }
    enum Direction
    class PlayerSetting <<ScriptableObject>>{
        +float AutoDropDelay
        +float ManualDropDelay
        +float StagnationTime
        +float MoveDelay
        +float RotateDelay
    }

    PlayerDrop --> PlayerState
    PlayerRotate --> PlayerState
    PlayerMove --> PlayerState
    PlayerRotate ..> Direction
    PlayerState *- Direction
    PlayerSetting <- PlayerState
}

namespace Items{
    interface Item
    class Bomb
    class Puyo{
        +PuyoType : PuyoType
    }
    class PuyoCollerTable <<ScriptableObject>>{
        +SerializableDictionary<PuyoType, Color> PuyoColooers
    }
    enum PuyoType

    Item <|-- Puyo
    Item <|-- Bomb
    Puyo --> PuyoCollerTable
    Puyo --> PuyoType
    PuyoCollerTable --> PuyoType
}

namespace Utility{
    class SerializableDictionary
    class ChainGauge
}

namespace Manager{
    class GameManager{
        +void OnGameOver()
    }
}


namespace Board{
    class WaitingBomb{
        +bool IsActive
        +int Count
    }

    class WatingItems{
        +(Item[] items, bool isBomb) GetNextPuyos()
    }

    class BoardController{
        {static} +Vector2Int START_POS
        +bool CanSettle(Vector2Int pos) 
        +bool Settle(Vector2Int pos, PuyoType puyoType)
        +bool DropToBottom()
        +void Explode(Vector2Int pos)
    }

    WaitingBomb <- WatingItems 
}

namespace Score{
    class ScoreData{
        +uint Value
        +void SetVisible(bool visible)
        +Unitask SetValue(uint targetValue, float seconds, float scale)
    }
    class ScoreManager{
        +Unitask AddScoreAddition(value)
        +Unitask AddScoreMultiplication(value)
        +void SetVisible(bool visible)
        +Unitask ResolveAddition()
        +Unitask ResolveMultiplication()
    }

    ScoreManager -> ScoreData
}




PlayerState --> Item
PlayerState --> BoardController
PlayerState --> WatingItems

WatingItems --> Item
BoardController --> Puyo
BoardController --> GameManager
BoardController -> ScoreManager

@enduml